In [3]:
import numpy as np

In [14]:
o = np.array([46,36,52,26,42,38])
e = np.array([40,40,40,40,40,40])

In [5]:
# chi Value

# ( O-E)^2/E

print (x2)


[0.9 0.4 3.6 4.9 0.1 0.1]


In [11]:
(o-e)**2

array([ 36,  16, 144, 196,   4,   4], dtype=int32)

In [12]:
np.sum((o-e)**2)

400

In [13]:
# find out total observed and expected

tot_o = np.sum(o)
tot_e = np.sum(e)

print (tot_o)
print (tot_e)

240
240


In [15]:
o-e

array([  6,  -4,  12, -14,   2,  -2])

In [16]:
(o-e)**2

array([ 36,  16, 144, 196,   4,   4], dtype=int32)

In [18]:
n = np.sum((o-e)**2)

In [19]:
d = tot_e

In [20]:
n/d

1.6666666666666667

In [21]:
n

400

In [22]:
tot_e

240

In [23]:
# function ;  Chi value

def chi_value(o,e):
    ...
    ...
    return chi

# Find the Chi square Critical value

In [24]:
from scipy.stats import chi2

In [26]:
alpha = 0.05
df = 5
chi_critical = chi2.isf(alpha,df)
print (chi_critical)

11.070497693516355
